version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: k00l3hPoshti
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
      - ./scripts:/scripts
    command: /bin/bash -c "/opt/mssql/bin/sqlservr & sleep infinity"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ConnectionStrings__DefaultConnection: Server=db;Database=db;User=sa;Password=k00l3hPoshti
    ports:
      - "5000:80"
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always
    networks:
      - app-network
networks:
  app-network: